[package]
name = "klint-rs"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
inquire = "0.9.4"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.10"
tree-sitter = "0.25"
tree-sitter-c-sharp = "0.23"
tree-sitter-python = "0.23"
tree-sitter-rust = "0.24"
tree-sitter-swift = "0.7"
tree-sitter-typescript = "0.23"
